### ISSUE TITLE
Feature Request - Lock X Axis in frame rate graph

### ISSUE THREAD

**Issue by winstano** [cirquit/trdrop#63] opened 2020-11-28 19:07 UTC
Absolutely loving this piece of software! Would it be possible to lock the X-Axis to 60? Right now the only way I can think to do it is to have a 60fps video running with a white frame rate line to 'lock' the graph at 60 and export it as an overlay, but I'd love to see the option to have a frame rate graph that doesn't move when it dips for more than a couple of seconds

**Comment by cirquit** [comment] 2020-12-25 21:02
Duplicate of #40, should be included in v1.1

**Comment by cirquit** [comment] 2020-12-28 18:46
Release is out.

**Closed by cirquit** 2020-12-28 18:46 UTC
Labels: duplicate, feature request
