### ISSUE TITLE
TRDrop takes up the entire screen + video render instead of images?

### ISSUE THREAD

**Issue by ENunn** [cirquit/trdrop#45] opened 2019-09-02 18:46 UTC
Trying out the new version of TrDrop but the program takes up the entire screen. 
![image](https://user-images.githubusercontent.com/19480682/64130432-cd4a7a00-cd87-11e9-9f0a-dca18c3d473b.png)

Also, is there any way to render to a video instead of having a ton of images in a folder? Pretty dissapointing that I've found nothing about it.

**Comment by illusion98** [comment] 2019-09-02 21:59
"Trying out the new version of TrDrop but the program takes up the entire screen."
Is a duplicate of #36 btw.

**Comment by ENunn** [comment] 2019-09-02 22:04
> "Trying out the new version of TrDrop but the program takes up the entire screen."
> Is a duplicate of #36 btw.

Ah.

What about the rendering? Any way to render to a video?

**Comment by cirquit** [comment] 2019-09-03 07:36
Thank you for trying trdrop! It's definitely possible, but I hesitated previously because of my lack of licensing knowledge. It seems to me that the encoder is licensed under LGPL, and my MIT license is even more "open", which should pose no problem.

I'll put it on the roadmap for the next big release. For the time being, please download [`ffmpeg` manually](https://ffmpeg.org/download.html) and run the following command in the export directory to create a video.

```bash
> ffmpeg -framerate 30 -i exportsequence_%10d.jpg  -c:v libx264 -pix_fmt yuv420p analysis.mp4
```

**Comment by samkarpenter** [comment] 2019-09-20 23:42
> Thank you for trying trdrop! It's definitely possible, but I hesitated previously because of my lack of licensing knowledge. It seems to me that the encoder is licensed under LGPL, and my MIT license is even more "open", which should pose no problem.
> 
> I'll put it on the roadmap for the next big release. For the time being, please download [`ffmpeg` manually](https://ffmpeg.org/download.html) and run the following command in the export directory to create a video.
> 
> ```shell
> > ffmpeg -framerate 30 -i exportsequence_%10d.jpg  -c:v libx264 -pix_fmt yuv420p analysis.mp4
> ```

It would have been great to have a video export function built in, preferably with sound. Great app for testing purposes. Thank you for taking the time to create it.

**Comment by cirquit** [comment] 2019-09-22 18:57
The sound export will most probably not be included in this feature as it does not scale to multiple videos. Then we could force people to pick one of the up to 3 sound tracks.

I would argue against this feature to keep this tool's functionality simple. Other tools are way more sophisticated to do sound muxing and I would like to not include the complexity of handling another information stream in the export functionality.  We want to focus on the analysis, not on video editing.

The video export on the other hand should be possible with the next release.

**Comment by Sunnysidee** [comment] 2019-10-18 12:04
> Thank you for trying trdrop! It's definitely possible, but I hesitated previously because of my lack of licensing knowledge. It seems to me that the encoder is licensed under LGPL, and my MIT license is even more "open", which should pose no problem.
> 
> I'll put it on the roadmap for the next big release. For the time being, please download [`ffmpeg` manually](https://ffmpeg.org/download.html) and run the following command in the export directory to create a video.
> 
> ```shell
> > ffmpeg -framerate 30 -i exportsequence_%10d.jpg  -c:v libx264 -pix_fmt yuv420p analysis.mp4
> ```

100% Apologize for this question as I am a useless at basic things but I downloaed the ffmpeg and did your command to create a video but I can't seem to find where this video is in my folders or anywhere. Any help with that? Thank for this program!

**Comment by cirquit** [comment] 2019-10-18 12:46
The video is the last argument of this command - in this case `analysis.mp4`. Check the [official ffmpeg](https://ffmpeg.org/ffmpeg.html#toc-Description) for further information.

**Comment by Sunnysidee** [comment] 2019-10-19 08:21
> The video is the last argument of this command - in this case `analysis.mp4`. Check the [official ffmpeg](https://ffmpeg.org/ffmpeg.html#toc-Description) for further information.

Thank you! It took me a while but I figured it out. This has been a game-changer for the work I do so I want to thank you for your hard work!

**Comment by cirquit** [comment] 2020-12-26 01:04
Will be closing this up as I'm not planning to include video encoding for now.

**Closed by cirquit** 2020-12-26 01:04 UTC
Labels: feature request
