### ISSUE TITLE
TRdrop take over entire screen when mouse hover over menu

### ISSUE THREAD

**Issue by tamodolo** [cirquit/trdrop#36] opened 2019-08-02 10:19 UTC
This is very annoying as the menu location don't update ending in me clicking outside window range. It seems that the fullscreen is just a layer that don't work as things are mapped to the original window. I tested this program with afterburner and found that it's using OpenGL to render the window.

sugestion to fix this: drop OGL as a window drawer. Dolphin-emu also uses QT so it should be a good reference material. As it is today the interface is beautifull but it isn't efficient.

Also, the interface seems to be made with touchscreen in mind because things uses too much space. I don't think this is the way people will use this program...

Congrats for making this amazing program! I'll continue to test and report any weird behavior I find.

**Comment by tamodolo** [comment] 2019-08-02 10:19
Forgot to mention: Tested in windows 10.

**Comment by cirquit** [comment] 2019-08-02 11:17
Unfortunately I don't know what you mean with "menu location don't update". Would you mind posting a screenshot with the buggy functionality?

I currently use the QQuickPaintedItem as the "Viewer" functionality, I think it's powered internally via OpenGL. I'll take a look into dolphin-emu when I correctly understood the problem you had.

The "touchscreen" feel is probably because I used QML instead of the (older, but well supported) Widgets API, with the Material Theme. And you're totally right, I don't plan to support Android/iOS.

I didn't adapt the theme or the elements for most cases, but this may be done in the future. Please create an issue where you propose a concrete improvement, preferably with a Screenshot of similar functionality in other programs or a sketch. This would help immensely! 

As I was developing this application I also noticed some bad design decisions (e.g floating windows instead of sidebar, think layer system of Photoshop) and this definitely will be up to future changes.

**Comment by tamodolo** [comment] 2019-08-02 22:41
This is a video I just made that shows the problem: https://drive.google.com/open?id=1UTAhIxNCOaCmy6JxIYDLQuGKT-a7wg6O

I'll open a new issue with some ideas for UI later as I find some reference material. For now, I think your idea about the sidebar with options is great (photoshop like).

Maybe taking a look at the old (but I think now ancient hehe) virtualdub as it have some good idea for simple design to simple show the video.

**Comment by cirquit** [comment] 2019-08-03 09:06
Oh, that one is definitely interesting. Thank you for the video. I'll try to reproduce it after fixing the memory issue.

As for virtualdub, it was possible to go into that "oldschool" look, but I wanted to create a more up-to-date user experience, which would hopefully translate slightly better on multiple systems. But for the functionality of the widgets I'll definitely take a look into it.

**Comment by illusion98** [comment] 2019-08-03 15:57
Same issue with Windows 10 1903

**Comment by cirquit** [comment] 2019-08-03 18:10
So, I tried to replicate the bug but I could not manage to do it. How do you get into the fullscreen mode without the title bar? If I simply go for the maximize button the bug does not happen.

**Comment by tamodolo** [comment] 2019-08-03 19:06
> 
> 
> So, I tried to replicate the bug but I could not manage to do it. How do you get into the fullscreen mode without the title bar? If I simply go for the maximize button the bug does not happen.

It's not a thing I do. When the mouse enters the clickable space of the button, trdrop goes to fullscreen. No clicks made.

**Comment by cirquit** [comment] 2019-08-03 19:28
Hmm. Can't reproduce this on my system. Could it be that some other program might do that?

In the next release, I'll force trdrop to only show up in fullscreen, please tell me if this mitigates the problem. Otherwise I think this is dependent on some qt internal implementation which I don't have the time to debug :(

**Comment by tamodolo** [comment] 2019-08-03 19:37
My install of windows is quite fresh as I just bought a new PC. I didn't find any other program that behave like that...

I'll test the new version and will report the behavior.

**Comment by tamodolo** [comment] 2019-08-03 19:52
I found what's causing it!

For some reason when the mouse enters the menu area the program switch the render mode to OGL. This causes the program to force fullscreen.

Here's a video showing the mode switch: https://drive.google.com/file/d/1Jr41tVu2o1h65C5PJt4re7Yt-R_BojAf/view?usp=sharing

**Comment by cirquit** [comment] 2019-08-03 19:55
That's interesting, I'll check if this behaviour is documented somewhere. But otherwise this issue is resolved?

**Comment by tamodolo** [comment] 2019-08-03 20:06
I think this solution is more like a workarround than a propper fix. Considering that the UI will change in near future this issue is somewhat fixed but at the cost of window mode as the fullscreen mode locks you out of the rest of the system (need to use alt + tab to switch to other programs).

My sugestion is to leave this open while thinking of other solution.

**Comment by cirquit** [comment] 2019-08-08 11:33
So it looks like next year Qt 6 will be released and they will move from OpenGL to a more native (DX for Windows) implementation. This may possibly remove this issue.

I currently do not know any other way than to rewrite the application with Widgets, which I don't have the time capacity for.

See [https://blog.qt.io/blog/2019/08/07/technical-vision-qt-6/](https://blog.qt.io/blog/2019/08/07/technical-vision-qt-6/)

**Comment by cirquit** [comment] 2020-12-26 00:52
So I removed the full screen requirement because of #45, I will take a look at Qt6 soon after finishing up all the issues. Closing to clean up.

**Closed by cirquit** 2020-12-26 00:52 UTC
Labels: bug
