### ISSUE TITLE
TRdrop always counts 60fps

### ISSUE THREAD

**Issue by karaokefreak** [cirquit/trdrop#47] opened 2019-10-16 13:02 UTC
Hi. 
First of all, thanks for creating this type of app. That said, well, it doesn't quite work for me.
I tried TRdrop with several games and it only worked twice. Ever since then the frame counter started saying that each of my captures is on 16ms frametime and 60 fps, although I deliberately chose games with a 30 fps cap for testing. 
I recorded raw avi for best possible quality.

Am I doing something wrong? Or is trdrop really messing up?

**Comment by illusion98** [comment] 2019-10-16 16:31
Turning on delta processing should reveal what's going with each / current frame and adjust the pixel difference to be less "_sensitive_". 
Duplicate of #41

**Comment by karaokefreak** [comment] 2019-10-16 18:59
> Turning on delta processing should reveal what's going with each / current frame and adjust the pixel difference to be less "_sensitive_".
> Duplicate of #41

Unfortunately, this did not solve the problem. In fact, enabling delta rendering caused ANOTHER problem; My footage starts going black and white with heavy contrast instead being colored. And the framecounter still remains at solid 60FPS

**Comment by karaokefreak** [comment] 2019-10-16 21:15
Ok, I think I might have found the issue, but I don't know how to solve it.
I capture with virtua dub, which uses Yuv in an uncompressed mode. When I used that for capturing footage from Nintendo switch and used delta rendering, every other frame (in a 30 fps game) was pitch black. I guess this is how TRdrop distinguishes a new frame from an old one.
HOWEVER my PS4 footage does not show black frames at all, even when a doubled frame comes up.  The frame in between, which should be black, is full of white artifacts. So I guess there is something wrong with the way the UHD-footage is captured. Can somebody give me some advice on how I  could fix this?

**Comment by cirquit** [comment] 2019-10-18 12:44
Your assumption is correct - the black/white images you see are purely for "debugging", to check why the framerate is calculated in the way it is. A black pixel means that between the last two frames **no changes** were detected, a white pixel means a changes was detected.

If you play with the `pixelDifference` in the settings, you can change the amount of difference which is allowed between the two pixels to still count as a duplicate. This is the setting you have to play around with to *calibrate* it to your the lossy capture (keep in mind this will be most probably give unreliable and uncomparable results).

As far as I know, the only way to collect lossless captures is to use a designated capture card.

**Comment by cirquit** [comment] 2020-12-25 21:06
Closing because it's old und not a specific trdrop issue.

**Closed by cirquit** 2020-12-25 21:06 UTC
Labels: duplicate
