### ISSUE TITLE
Option to set static graph height and interval

### ISSUE THREAD

**Issue by o1230sponge** [cirquit/trdrop#50] opened 2020-02-02 19:49 UTC
I believe an option to have the framerate and frametime graphs to have a static maximum with customizable intervals should exist. 
For example, to have the top of the graph always be 60/30 fps, and have the option to set the interval to count up.
Like a graph with the intervals  0, 6, 12, 18, 24, and 30 could be accomplished with an interval of 6 option. Or an interval of 10 option would give a 0, 10, 20, 30.

**Comment by illusion98** [comment] 2020-02-03 04:30
Duplicate of #40

**Closed** 2020-10-21 09:08 UTC
